services:
  aninhi-bot-dev:
    build: .
    container_name: aninhi-discord-bot-dev
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - DATABASE_URL=file:./data/database.db
      - DEBUG=bot:*
    volumes:
      # Mount source code để hot reload
      - .:/app
      - /app/node_modules
      # Mount thư mục data
      - ./data:/app/data
      # Mount logs
      - ./logs:/app/logs
    networks:
      - aninhi-network-dev
    command: ["yarn", "dev"]
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('Dev bot is running')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Service để khởi tạo database trong development
  database-init-dev:
    build: .
    container_name: aninhi-db-init-dev
    environment:
      - DATABASE_URL=file:./data/database.db
    volumes:
      - .:/app
      - /app/node_modules
      - ./data:/app/data
    command: >
      sh -c "
        npx prisma generate &&
        npx prisma migrate dev --name init &&
        echo 'Development database initialized successfully'
      "
    profiles:
      - init

networks:
  aninhi-network-dev:
    driver: bridge

volumes:
  data:
  logs: 